import torch
import torch.nn as nn

lvbb = nn.Sequential(nn.Conv2d(3,64,3,1,1),
                     # nn.BatchNorm2d(64),
                     nn.InstanceNorm2d(64),
                     nn.ReLU(inplace=True),
                     nn.Conv2d(64,64,3,1,1),
                     # nn.BatchNorm2d(64),
                     nn.InstanceNorm2d(64),
                     nn.ReLU(inplace=True),
                     nn.MaxPool2d(2,2,padding=0,dilation=1),
                     nn.Conv2d(64,128,3,1,1),
                     # nn.BatchNorm2d(128),
                     nn.InstanceNorm2d(128),
                     nn.ReLU(inplace=True),
                     nn.Conv2d(128,128,3,1,1),
                     # nn.BatchNorm2d(128),
                     nn.InstanceNorm2d(128),
                     nn.ReLU(inplace=True),
                     nn.MaxPool2d(2,2,padding=0,dilation=1),
                     nn.Conv2d(128,256,3,1,1),
                     # nn.BatchNorm2d(256),
                     nn.InstanceNorm2d(256),
                     nn.ReLU(inplace=True),
                     nn.Conv2d(256,256,3,1,1),
                     # nn.BatchNorm2d(256),
                     nn.InstanceNorm2d(256),
                     nn.ReLU(inplace=True),
                     nn.Conv2d(256,256,3,1,1),
                     # nn.BatchNorm2d(256),
                     nn.InstanceNorm2d(256),
                     nn.ReLU(inplace=True),
                     nn.MaxPool2d(2,2,padding=0,dilation=1),
                     nn.Conv2d(256, 512, 3, 1, 1),
                     # nn.BatchNorm2d(512),
                     nn.InstanceNorm2d(512),
                     nn.ReLU(inplace=True),
                     nn.Conv2d(512, 512, 3, 1, 1),
                     # nn.BatchNorm2d(512),
                     nn.InstanceNorm2d(512),
                     nn.ReLU(inplace=True),
                     nn.Conv2d(512, 512, 3, 1, 1),
                     # nn.BatchNorm2d(512),
                     nn.InstanceNorm2d(512),
                     nn.ReLU(inplace=True),
                     nn.MaxPool2d(2, 2, padding=0, dilation=1),
                     nn.Conv2d(512, 512, 3, 1, 1),
                     # nn.BatchNorm2d(512),
                     nn.InstanceNorm2d(512),
                     nn.ReLU(inplace=True),
                     nn.Conv2d(512, 512, 3, 1, 1),
                     # nn.BatchNorm2d(512),
                     nn.InstanceNorm2d(512),
                     nn.ReLU(inplace=True),
                     nn.Conv2d(512, 512, 3, 2, 1),
                     # nn.BatchNorm2d(512),
                     nn.InstanceNorm2d(512),
                     nn.ReLU(inplace=True),
                     nn.MaxPool2d(2, 2, padding=0, dilation=1))


